[
  # Generated by `use AshPostgres.Repo`: all_tenants/0 raises by design when
  # schema-based multitenancy isn't used (org scoping is by organization_id).
  {"lib/sertantai_compliance/repo.ex", :no_return}
]
