[
  # Generated by `use AshPostgres.Repo`: all_tenants/0 raises by design when
  # schema-based multitenancy isn't used (org scoping is by organization_id).
  {"lib/sertantai_compliance/repo.ex", :no_return},

  # OTP 28+ false positives: MapSet wraps the opaque :sets.set, and Dialyzer
  # flags idiomatic MapSet.member?/to_list calls as call_without_opaque.
  # Known upstream (elixir-lang/elixir#14750, #14576); keep code idiomatic and
  # ignore narrowly per file rather than rewriting around it.
  {"lib/sertantai_compliance/baserow/client.ex", :call_without_opaque},
  {"lib/sertantai_compliance/baserow/schema_manager.ex", :call_without_opaque},
  {"lib/sertantai_compliance/sync/engine.ex", :call_without_opaque},
  {"lib/sertantai_compliance/sync/templates/applicator.ex", :call_without_opaque},
  {"lib/sertantai_compliance/sync/templates/registry.ex", :call_without_opaque}
]
