defmodule SertantaiCompliance.Repo.Migrations.AddLawChangeSnapshots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create_if_not_exists table(:law_change_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :law_name, :text, null: false
      add :live, :text
      add :amended_by, {:array, :text}, default: []
      add :rescinded_by, {:array, :text}, default: []
      add :in_corpus, :boolean, default: false

      add :snapshot_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create_if_not_exists unique_index(:law_change_snapshots, [:law_name],
                           name: "law_change_snapshots_unique_law_index"
                         )
  end

  def down do
    drop_if_exists unique_index(:law_change_snapshots, [:law_name],
                     name: "law_change_snapshots_unique_law_index"
                   )

    drop_if_exists table(:law_change_snapshots)
  end
end
