defmodule SertantaiCompliance.Repo.Migrations.AddProfileConditions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  # Idempotent: the table is shared with sertantai-legal in dev (see CLAUDE.md).
  use Ecto.Migration

  def up do
    alter table(:org_screening_profiles) do
      add_if_not_exists :conditions, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:org_screening_profiles) do
      remove_if_exists :conditions, {:array, :text}
    end
  end
end
