defmodule SertantaiCompliance.Repo.Migrations.InitialSyncTables do
  @moduledoc """
  Creates compliance-owned Sync domain tables.

  Idempotent: safe to run against databases where these tables already exist
  (e.g. production DB previously managed by sertantai-legal).

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  and then made idempotent for production adoption.
  """

  use Ecto.Migration

  def up do
    # --- Tables (idempotent) ---

    create_if_not_exists table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create_if_not_exists table(:sync_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :name, :text, null: false
      add :description, :text
      add :families, {:array, :text}, null: false
      add :geo_regions, {:array, :text}
      add :function_filter, :map
      add :fitness_entities, {:array, :text}
      add :live_filter, {:array, :text}
      add :include_lat, :boolean, null: false, default: false
      add :include_amendments, :boolean, null: false, default: false
      add :matched_law_count, :bigint
      add :matched_lat_count, :bigint
      add :is_active, :boolean, null: false, default: true
      add :deactivation_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create_if_not_exists table(:sync_configurations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false

      add :sync_profile_id,
          references(:sync_profiles,
            column: :id,
            name: "sync_configurations_sync_profile_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :name, :text, null: false
      add :provider, :text, null: false
      add :encrypted_credentials, :text, null: false
      add :credentials_iv, :text, null: false
      add :target_config, :map, null: false
      add :field_mapping, :map
      add :sync_frequency, :text, null: false
      add :on_filter_change, :text, null: false, default: "delete"
      add :on_entitlement_change, :text, null: false, default: "delete"
      add :sync_status, :text, null: false, default: "idle"
      add :last_synced_at, :utc_datetime_usec
      add :last_sync_summary, :map
      add :is_active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create_if_not_exists table(:sync_jobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :sync_configuration_id,
          references(:sync_configurations,
            column: :id,
            name: "sync_jobs_sync_configuration_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organization_id, :uuid, null: false
      add :status, :text, null: false, default: "queued"
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :law_count, :bigint
      add :lat_count, :bigint
      add :rows_created, :bigint, null: false, default: 0
      add :rows_updated, :bigint, null: false, default: 0
      add :rows_deleted, :bigint, null: false, default: 0
      add :rows_failed, :bigint, null: false, default: 0
      add :error_message, :text
      add :error_details, :map
      add :sync_checkpoint, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create_if_not_exists table(:sync_row_mappings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :sync_configuration_id,
          references(:sync_configurations,
            column: :id,
            name: "sync_row_mappings_sync_configuration_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :source_type, :text, null: false
      add :source_id, :text, null: false
      add :external_row_id, :bigint, null: false
      add :last_synced_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create_if_not_exists table(:org_entitlements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :families, {:array, :text}, null: false
      add :data_tier, :text, null: false
      add :field_tier, :text, null: false
      add :source, :text, null: false
      add :granted_at, :utc_datetime_usec, null: false
      add :expires_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create_if_not_exists table(:org_applicabilities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :law_name, :text, null: false
      add :status, :text, null: false, default: "unreviewed"
      add :source, :text, null: false
      add :notes, :text
      add :reviewed_at, :utc_datetime_usec
      add :reviewed_by, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create_if_not_exists table(:org_secondary_applicabilities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :source_id, :text, null: false
      add :status, :text, null: false, default: "unreviewed"
      add :source, :text, null: false
      add :notes, :text
      add :reviewed_at, :utc_datetime_usec
      add :reviewed_by, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create_if_not_exists table(:org_screening_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :regions, {:array, :text}, default: []
      add :governed_actors, {:array, :text}, default: []
      add :government_actors, {:array, :text}, default: []
      add :activities, {:array, :text}, default: []
      add :locations, {:array, :text}, default: []
      add :materials, {:array, :text}, default: []
      add :processes, {:array, :text}, default: []
      add :sector, {:array, :text}, default: []
      add :certifications, {:array, :text}, default: []
      add :contract_requirements, {:array, :text}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create_if_not_exists table(:applicability_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :law_name, :text, null: false
      add :event, :text, null: false
      add :actor, :text, null: false
      add :status_before, :text
      add :status_after, :text, null: false
      add :source, :text, null: false
      add :metadata, :map
      add :materiality, :text
      add :decision, :text
      add :decision_reason, :text
      add :review_due_date, :date

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    # --- Unique indexes (idempotent) ---

    create_if_not_exists unique_index(:organizations, [:id],
                           name: "organizations_unique_id_index"
                         )

    create_if_not_exists unique_index(
                           :sync_row_mappings,
                           [:sync_configuration_id, :source_type, :source_id],
                           name: "sync_row_mappings_unique_mapping_index"
                         )

    create_if_not_exists unique_index(:org_entitlements, [:organization_id],
                           name: "org_entitlements_unique_org_index"
                         )

    create_if_not_exists unique_index(:org_applicabilities, [:organization_id, :law_name],
                           name: "org_applicabilities_unique_org_law_index"
                         )

    create_if_not_exists unique_index(
                           :org_secondary_applicabilities,
                           [:organization_id, :source_id],
                           name: "org_secondary_applicabilities_unique_org_source_index"
                         )

    create_if_not_exists unique_index(:org_screening_profiles, [:organization_id],
                           name: "org_screening_profiles_unique_org_index"
                         )

    # --- FK constraints (idempotent via DO $$ checks) ---

    execute(
      """
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sync_jobs_sync_configuration_id_fkey') THEN
          ALTER TABLE sync_jobs
            ADD CONSTRAINT sync_jobs_sync_configuration_id_fkey
            FOREIGN KEY (sync_configuration_id) REFERENCES sync_configurations(id);
        END IF;
      END $$;
      """,
      "ALTER TABLE sync_jobs DROP CONSTRAINT IF EXISTS sync_jobs_sync_configuration_id_fkey"
    )

    execute(
      """
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sync_row_mappings_sync_configuration_id_fkey') THEN
          ALTER TABLE sync_row_mappings
            ADD CONSTRAINT sync_row_mappings_sync_configuration_id_fkey
            FOREIGN KEY (sync_configuration_id) REFERENCES sync_configurations(id);
        END IF;
      END $$;
      """,
      "ALTER TABLE sync_row_mappings DROP CONSTRAINT IF EXISTS sync_row_mappings_sync_configuration_id_fkey"
    )

    execute(
      """
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sync_configurations_sync_profile_id_fkey') THEN
          ALTER TABLE sync_configurations
            ADD CONSTRAINT sync_configurations_sync_profile_id_fkey
            FOREIGN KEY (sync_profile_id) REFERENCES sync_profiles(id);
        END IF;
      END $$;
      """,
      "ALTER TABLE sync_configurations DROP CONSTRAINT IF EXISTS sync_configurations_sync_profile_id_fkey"
    )
  end

  def down do
    drop_if_exists table(:applicability_events)
    drop_if_exists table(:org_screening_profiles)
    drop_if_exists table(:org_secondary_applicabilities)
    drop_if_exists table(:org_applicabilities)
    drop_if_exists table(:org_entitlements)
    drop_if_exists table(:sync_row_mappings)
    drop_if_exists table(:sync_jobs)
    drop_if_exists table(:sync_configurations)
    drop_if_exists table(:sync_profiles)
    drop_if_exists table(:organizations)
  end
end
